### ISSUE TITLE
Open to adding other maintainers?

### ISSUE THREAD

**Issue by zenspider** [bhuga/faraday-restrict-ip-addresses#11]
See title... this gem is still in use in the wild but I suspect most are running off of private forks. Care to add some maintainers to keep this moving?

**Comment by bhuga** [comment]
> Care to add some maintainers to keep this moving?

That's fine. Would you like to be one?

**Comment by zenspider** [comment]
Yeah. I'm down.

**Comment by bhuga** [comment]
Done. Sorry for the delay. Thanks for stepping up :bow:

**Comment by zenspider** [comment]
Accepted. Thanks. Just sent you an email to see if you have time to get on a call to sync up.

**Comment by zenspider** [comment]
@bhuga sorry to bother... may I have admin? and/or I don't see the workflows actually running for some reason.

**Comment by bhuga** [comment]
Unfortunately, no?

According to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository#changing-permissions-for-a-team-or-person, I should be able to grant this, but there is no 'role' dropdown on that page :/
