### ISSUE TITLE
Setup ??

### ISSUE THREAD

**Issue by austinklenk** [bhuga/faraday-restrict-ip-addresses#4]
How exactly do you incorporate this in to a rails app?
i know the basic with putting it in the gem file and bundling the gem

where do you put

`faraday = Faraday.new do |builder|
  builder.request :url_encoded
  builder.request :restrict_ip_addresses, deny_rfc6890: true,
                                          allow_localhost: false,
                                          deny: ['8.0.0.0/8',
                                                 '224.0.0.0/7'],
                                          allow: ['192.168.0.0/24']
  builder.adapter Faraday.default_adapter
end`

**Comment by bhuga** [comment]
This isn't a rails plugin per se, it only affects usage of Faraday. You need to pass the faraday client that you've constructed as in the README to wherever you're already using Faraday.

**Comment by zenspider** [comment]
closing as stale
