### ISSUE TITLE
Review Coinbase's DNS rebinding mitigation

### ISSUE THREAD

**Issue by amacdougall** [bhuga/faraday-restrict-ip-addresses#9]
Some engineers from Coinbase forked this repo to add a security fix. The two repos are now divergent. If their fix has merit, it would be great to see it in the main repo.

https://github.com/coinbase/faraday-restrict-ip-addresses

Feel free to close this issue if you decide not to include those changes.

Context: an app I'm working on has a reference to the Coinbase fork in its Gemfile, but I'm interested in bringing the gem completely up to date. It would be great to replace the Github reference with a standard gem reference again.

**Comment by bhuga** [comment]
I'd love to include those changes, but licensing is potentially weird if I go get the commits as opposed to them submitting a PR. @jimpo, @aianus, any interest in submitting your coinbase patches upstream?

**Comment by amacdougall** [comment]
Thanks for the quick response! For now, we'll just maintain (yet another) fork on our private repo, but I'll watch this space.

**Comment by amacdougall** [comment]
Actually I just checked LinkedIn, and unfortunately, neither of those devs are still with Coinbase. But I might have a sidechannel to Coinbase development, and failing that, maybe @jimpo or @aianus can forward this to one of their former colleagues who is still there.

**Comment by jimpo** [comment]
@zquestz Anyone at CB interested in upstreaming changes to dependencies?

**Comment by aianus** [comment]
@bhuga @amacdougall 

Just a heads up, the rebinding mitigation also involved patches to Net::HTTP and the faraday Net::HTTP connection adapter.

Specifically, they both had to be patched to pass this sni_host parameter all the way through to the SSLSocket: https://github.com/coinbase/faraday-restrict-ip-addresses/blob/master/lib/faraday/restrict_ip_addresses.rb#L77

This was the reason I didn't originally try to push these changes upstream but if you guys are interested, an example Net::HTTP monkey patch is here: https://gist.github.com/aianus/20930914155b270d66c404c1e43e89ed and the faraday changes are here: https://github.com/aianus/faraday/commits/master

**Comment by amacdougall** [comment]
Interesting... the developer who originally included your fix in our Gemfile didn't add any of those other changes, and might not have been aware of them. We'll have to decide about the risk/reward profile on this one.

**Comment by amacdougall** [comment]
We ultimately decided to switch to mainline. Our threat profile is very different from that of Coinbase, so implementing the full mitigation didn't seem worthwhile.
